//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agents()
        {
            this.ProductSales = new HashSet<ProductSales>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdTypeAgent { get; set; }
        public string NameAgent { get; set; }
        public string EmailAgent { get; set; }
        public string PhoneAgent { get; set; }
        public string LogoAgent { get; set; }
        public string Adress { get; set; }
        public int Priority { get; set; }
        public string Director { get; set; }
        public long INN { get; set; }
        public long KPP { get; set; }
    
        public virtual TypeAgent TypeAgent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSales> ProductSales { get; set; }
    }
}
